# Generated by Django 4.0 on 2022-04-08 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
