# Generated by Django 4.0 on 2022-04-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=300)),
                ('l_name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
