# Generated by Django 4.0 on 2022-04-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Update',
        ),
    ]
