# Generated by Django 4.0 on 2022-04-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='city',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='country',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='state',
        ),
        migrations.AddField(
            model_name='checkout',
            name='contact',
            field=models.IntegerField(default=False),
        ),
    ]
