# Generated by Django 4.0 on 2022-04-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_checkout_city_remove_checkout_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='zip_code',
            field=models.IntegerField(default=False),
        ),
    ]
