# Generated by Django 4.0 on 2022-04-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_checkout_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='contact',
            new_name='phone',
        ),
    ]
