# Generated by Django 4.0 on 2022-04-09 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Update',
        ),
    ]
